### ISSUE TITLE
rethink default mode for SetConsoleMode

### ISSUE THREAD

**Issue by hellow554** [kumavale/getch-rs#6]
Currently the previous mode will be used just as it was:

https://github.com/kumavale/getch-rs/blob/f0611a226a6660f03d30033bf8b0a5f1d3dbf840/src/lib.rs#L83-L88

but I noticed for example, that <kbd>ctrl</kbd> + <kbd>c</kbd> will not be passed to the application, but instead windows handels it.
This is due `ENABLE_PROCESSED_INPUT` is set: https://learn.microsoft.com/en-us/windows/console/setconsolemode

I think we should set a reasonable default for the terminal, instead of relying the previous behavior.

I currently can only think of the `ENABLE_VIRTUAL_TERMINAL_INPUT` as a valid value, all others don't really fit in here.

What do you think?

**Comment by kumavale** [comment]
Thanks for the issue.  
Surely you are correct in setting only `ENABLE_VIRTUAL_TERMINAL_INPUT` as a valid value.
